#!/usr/bin/env bash
#
# *Do not use quotes with variable assignments!*
#
# ---
#
# references:
# https://wiki.archlinux.org/title/XDG_Base_Directory

# Temp directory
export TMPDIR=${TMPDIR:-/tmp}

# XDG
export XDG_DATA_HOME=${XDG_DATA_HOME:-${HOME}/.local/share}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-${HOME}/.config}
export XDG_STATE_HOME=${XDG_STATE_HOME:-${HOME}/.local/state}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-${HOME}/.cache}
export XDG_BIN_HOME=${XDG_BIN_HOME:-${HOME}/.local/bin}
export XDG_RUNTIME_DIR=${TMPDIR%\/}

# General
export EDITOR=${EDITOR:-nvim}
export VISUAL=${VISUAL:-nvim}
export PAGER=${PAGER:-less}
export BROWSER=${BROWSER:-open}
export LANG=${LANG:-en_US.UTF-8}
export LC_ALL=${LANG}

# Bash
export BASH_COMPLETION_USER_FILE=${XDG_CONFIG_HOME}/bash-completion/bash_completion

# Less
export LESS=${LESS:--g -i -M -R -S -w -z-4}
export LESSHISTFILE=${XDG_STATE_HOME}/less/history

# Node
export NPM_CONFIG_USERCONFIG=${XDG_CONFIG_HOME}/npm/npmrc
export NPM_CONFIG_CACHE=${XDG_CACHE_HOME}/npm
export PNPM_HOME=${XDG_DATA_HOME}/pnpm
export NODE_REPL_HISTORY=${XDG_DATA_HOME}/node_repl_history

# Homebrew
if [[ -e /usr/local/bin/brew ]]; then
  export HOMEBREW_PREFIX=/usr/local
elif [[ -e /opt/homebrew/bin/brew ]]; then
  export HOMEBREW_PREFIX=/opt/homebrew
fi
if [[ ${HOMEBREW_PREFIX} ]]; then
  eval "$("${HOMEBREW_PREFIX}"/bin/brew shellenv)"
  export HOMEBREW_NO_ANALYTICS=1
fi

# Misc.
export SHELL_SESSIONS_DISABLE=1    # Make Apple Terminal behave
export DISABLE_AUTO_TITLE='true'   # Tmux auto title

# 1Password SSH agent
if [[ ${OSTYPE} == 'darwin'* && ! ${SSH_TTY} ]]; then
  export SSH_AUTH_SOCK=${HOME}/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock
fi

# PATH
export PATH=${XDG_DATA_HOME}/npm-global/bin:${PATH}
export PATH=${PNPM_HOME}:${PATH}

export PATH=${XDG_BIN_HOME}:${PATH} #! **keep it last**

