## Brew taps
tap "buildpack/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "tavianator/tap"
# tap "windmilleng/tap"

## Essential brew packages
brew "bash-completion"
brew "antigen"
brew "python"
brew "ccat"
brew "curl"
brew "editorconfig"
brew "fzf"
brew "git"
brew "git-flow"
brew "git-subrepo"
brew "hub"
brew "icdiff"
brew "jq"
brew "highlight"
brew "kubernetes-cli"
brew "mackup"
brew "neovim"
brew "nnn"
brew "node"
brew "youtube-dl"
brew "reattach-to-user-namespace"
brew "python@2"
brew "rename"
brew "ripgrep"
brew "tig"
brew "tmux"
brew "tree"
brew "tvnamer"
brew "unzip"
brew "watch"
brew "wget"
brew "zsh"
brew "tavianator/tap/bfs"

## Other brew packages
# brew "httpstat"
# brew "ffmpeg"
# brew "aria2"
# brew "sqlite"
# brew "b2-tools"
# brew "fontconfig"
# brew "extract_url"
# brew "gnu-sed"
# brew "hyperkit", link: false
# brew "jupyter"
# brew "pacvim"
# brew "pipenv"
# brew "ranger"
# brew "travis"
# brew "riff"
# brew "yarn"
# brew "buildpack/tap/pack"
# brew "windmilleng/tap/tilt"

## macOS essential Apps
cask "1password"
cask "dash"
cask "setapp"
cask "wd-security"
cask "spectacle"
cask "slack"
cask "visual-studio-code"
cask "hazel"
cask "iterm2"
cask "now"
cask "popclip"
cask "safari-technology-preview"
cask "google-chrome"
cask "google-chrome-canary"
cask "google-cloud-sdk"
cask "firefox-developer-edition"
cask "font-fira-code"
cask "itunes-volume-control"
cask "dropbox"

## For iMac ONLY
### macOS Apps
# cask "carbon-copy-cloner"
# cask "plex-media-server"
# cask "google-photos-backup-and-sync"
# cask "megasync"
# cask "docker-edge"
# cask "drobo-dashboard"

## Other macOS Apps
# cask "vectr"
# cask "tidal"
# cask "postgres"
# cask "resilio-sync"
# cask "revisions"
# cask "miniconda"
# cask "minikube"
# cask "ngrok"
# cask "git-it"
# cask "wd-firmware-updater"
# cask "steam"
# cask "transmit"
# cask "vlc"
# cask "malwarebytes"
# cask "expressvpn"
# cask "framer-x"
# cask "db-browser-for-sqlite"
# cask "xquartz"
#
# EOF managed list
