{pkgs, ...}: {
  imports = [
    # Generated by OrbStack.
    /etc/nixos/configuration.nix
  ];

  # Limit the number of generations to keep
  boot.loader.systemd-boot.configurationLimit = 5;

  nix.settings = {
    experimental-features = ["nix-command" "flakes"];
    use-xdg-base-directories = true;
    auto-optimise-store = true;
  };

  environment.shells = with pkgs; [bash zsh];
  users.defaultUserShell = pkgs.zsh;

  programs = {
    zsh.enable = true;
    nix-ld = {
      enable = true;
      package = pkgs.nix-ld-rs;
      libraries = with pkgs; [glib];
    };
  };
}
